# Generated by Django 4.1.3 on 2023-04-11 14:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('body', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('mis_a_jour', models.DateField(auto_now=True)),
                ('status', models.DateField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=200)),
                ('heure_publication', models.DateField(default=datetime.datetime(2023, 4, 11, 14, 9, 4, 742461, tzinfo=datetime.timezone.utc))),
                ('category', models.CharField(default='Actualité', max_length=255)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='inconnu', max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_modify', models.DateField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.post')),
            ],
        ),
    ]
