# Generated by Django 4.1.3 on 2023-04-16 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heure_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 16, 21, 55, 11, 404807, tzinfo=datetime.timezone.utc)),
        ),
    ]
