# Generated by Django 4.1.3 on 2023-04-17 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_category_alter_post_heure_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heure_publication',
        ),
        migrations.AddField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 9, 35, 49, 699162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_post', to='Blog.category'),
        ),
    ]
