# Generated by Django 4.1.3 on 2023-04-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_post_heure_publication_post_date_publication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 17, 10, 3, 54, 892656, tzinfo=datetime.timezone.utc)),
        ),
    ]
