# Generated by Django 4.1.3 on 2023-04-20 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_post_category_remove_post_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Actualité', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 20, 6, 4, 23, 732859, tzinfo=datetime.timezone.utc)),
        ),
    ]
