# Generated by Django 4.1.3 on 2023-04-24 11:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_alter_comment_options_post_category_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='Blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 11, 41, 30, 127228, tzinfo=datetime.timezone.utc)),
        ),
    ]
