# Generated by Django 4.1.3 on 2023-04-24 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_category_slug_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_publication',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 11, 43, 28, 304393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
